### ISSUE TITLE
IfcCovering Relationships & Documentation

### ISSUE THREAD

**Issue by AlexBrad1eyCT** [bSI-InfraRoom/IFC-Specification#62]
Placeholder will Update ASAP

**Comment by SergejMuhic** [comment]
Resolved in #64

**Comment by AlexBrad1eyCT** [comment]
Not resolved but needs to be in backlog, #64 only addresses IfcSurfaceFeature

**Comment by SergejMuhic** [comment]
Which part still needs to be addressed? Could you write up the issue instead of a placeholder?
